name: 'linting'

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  lint:
    runs-on: 'ubuntu-latest'

    strategy:
      matrix:
        node-version: ['lts/*']
      fail-fast: false

    steps:
      - name: 'Checkout Project'
        uses: 'actions/checkout@v2'
        with:
          fetch-depth: 0

      - name: Use Node.js ${{ matrix.node-version }}
        uses: 'actions/setup-node@v3.0.0'
        with:
          node-version: ${{ matrix.node-version }}

      - name: 'Cache Node dependencies'
        uses: 'actions/cache@v2'
        with:
          path: '~/.npm'
          key: ${{ runner.os }}-node-${{ hashFiles('**/package.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: 'Install Dependencies'
        run: 'npm install'

      - name: 'Run Tests'
        run: 'npm run check'
